def on_a_pressed():
    global projectile
    projectile = sprites.create_projectile_from_sprite(img("""
            . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . f f f f . . . . . . . 
                    . . . . . . . . f . . . . . . . 
                    . . . . . . . . . f f . . . . . 
                    . . . . . . f f . . f . . . . . 
                    . . . . . . . f . . f . . . . . 
                    . . . . . . f f . . f . . . . . 
                    . . . . . . f . . . f . . . . . 
                    . . . . . . . . . f . . . . . . 
                    . . . . . . . f f f . . . . . . 
                    . . . . . f f f . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . .
        """),
        mySprite,
        120,
        0)
    pause(100)
    sprites.destroy(projectile)
    animation.run_image_animation(mySprite,
        [img("""
                ........................
                        ....ffffff..............
                        ..ffeeeef2f.............
                        .ffeeeef222f............
                        .feeeffeeeef...cc.......
                        .ffffee2222ef.cdc.......
                        .fe222ffffe2fcddc.......
                        fffffffeeeffcddc........
                        ffe44ebf44ecddc.........
                        fee4d41fddecdc..........
                        .feee4dddedccc..........
                        ..ffee44e4dde...........
                        ...f222244ee............
                        ...f2222e2f.............
                        ...f444455f.............
                        ....ffffff..............
                        .....fff................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ........................
                        .......fff..............
                        ....fffff2f.............
                        ..ffeeeee22ff...........
                        .ffeeeeee222ff..........
                        .feeeefffeeeef..........
                        .fffffeee2222ef.........
                        fffe222fffffe2f.........
                        fffffffffeeefff.....cc..
                        fefe44ebbf44eef...ccdc..
                        .fee4d4bbfddef..ccddcc..
                        ..feee4dddddfeecdddc....
                        ...f2222222eeddcdcc.....
                        ...f444445e44ddccc......
                        ...ffffffffeeee.........
                        ...fff...ff.............
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                .......ff...............
                        ....ffff2ff.............
                        ..ffeeeef2ff............
                        .ffeeeeef22ff...........
                        .feeeeffeeeef...........
                        .fffffee2222ef..........
                        fffe222ffffe2f..........
                        ffffffffeeefff..........
                        fefe44ebf44eef..........
                        .fee4d4bfddef...........
                        ..feee4dddee.c..........
                        ...f2222eeddeccccccc....
                        ...f444e44ddecddddd.....
                        ...fffffeeee.ccccc......
                        ..ffffffff...c..........
                        ..fff..ff...............
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                ....ffffff..............
                        ..ffeeeef2f.............
                        .ffeeeef222f............
                        .feeeffeeeef............
                        .ffffee2222ef...........
                        .fe222ffffe2f...........
                        fffffffeeefff...........
                        ffe44ebf44eef...........
                        fee4d41fddef............
                        .feee4ddddf.............
                        ..fdde444ef.............
                        ..fdde22ccc.............
                        ...eef22cdc.............
                        ...f4444cddc............
                        ....fffffcddc...........
                        .....fff..cddc..........
                        ...........cdc..........
                        ............cc..........
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
            """),
            img("""
                . . . f f f f f f f f f . . . 
                        . . f f a a a a a a a f f . . 
                        . . f a a a a a a a a a f . . 
                        . . f a a a a a a a a a f . . 
                        . . f a a a a a a f f a f . . 
                        . . f a a d a a f 1 8 d f . . 
                        . . f a a d a a d 1 8 d f . . 
                        . . f a a d a a d d d f f . . 
                        . . f a a 9 a 7 7 7 f f . . . 
                        . . f a a 6 6 9 7 7 f . . . . 
                        . . f f a 6 6 9 9 9 f . . . . 
                        . . . f f 6 6 9 9 9 f . . . . 
                        . . . . f 9 9 9 9 9 f . . . . 
                        . . . . f f f f f f f . . . . 
                        . . . . . f e e e f . . . . . 
                        . . . . . . f f f . . . . . .
            """)],
        100,
        False)
    pause(100)
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def Level():
    Level()

def on_on_overlap(sprite, otherSprite):
    sprites.destroy(projectile)
sprites.on_overlap(SpriteKind.projectile, SpriteKind.enemy, on_on_overlap)

projectile: Sprite = None
mySprite: Sprite = None
mySprite = sprites.create(img("""
        . . . f f f f f f f f f . . . 
            . . f f a a a a a a a f f . . 
            . . f a a a a a a a a a f . . 
            . . f a a a a a a a a a f . . 
            . . f a a a a a a f f a f . . 
            . . f a a d a a f 1 8 d f . . 
            . . f a a d a a d 1 8 d f . . 
            . . f a a d a a d d d f f . . 
            . . f a a 9 a 7 7 7 f f . . . 
            . . f a a 6 6 9 7 7 f . . . . 
            . . f f a 6 6 9 9 9 f . . . . 
            . . . f f 6 6 9 9 9 f . . . . 
            . . . . f 9 9 9 9 9 f . . . . 
            . . . . f f f f f f f . . . . 
            . . . . . f e e e f . . . . . 
            . . . . . . f f f . . . . . .
    """),
    SpriteKind.player)
mySprite.y = 75
mySprite.ay = 500
controller.move_sprite(mySprite)
tiles.set_current_tilemap(tilemap("""
    level2
"""))

def on_forever():
    pass
forever(on_forever)
